In [1]:
# !pip install yfinance

In [1]:
from urllib import request
import yfinance as yf
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing, model_selection, svm
from plotly.offline import plot
import plotly.graph_objects as go
import plotly.express as px
from plotly.graph_objs import Scatter
import pandas as pd
from sklearn import preprocessing
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import datetime as dt
import numpy as np

from tensorflow import keras
from sklearn import preprocessing
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping

C:\Users\sushant\anaconda3\envs\project\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\sushant\anaconda3\envs\project\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\Users\sushant\anaconda3\envs\project\lib\site-packages\numpy\.libs\libopenblas.wcdjnk7yvmpzq2me2zzhjjrj3jikndb7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [2]:
data = yf.download(
        
    # passes the ticker
    tickers=['AAPL', 'AMZN', 'QCOM', 'META', 'NVDA', 'JPM'],

    group_by = 'ticker',

    threads=True, # Set thread value to true

    # used for access data[ticker]
    period='12mo', 
    interval='1d'

)

data.reset_index(level=0, inplace=True)



fig_left = go.Figure()
fig_left.add_trace(
            go.Scatter(x=data['Date'], y=data['AAPL']['Adj Close'], name="AAPL")
        )
fig_left.add_trace(
            go.Scatter(x=data['Date'], y=data['AMZN']['Adj Close'], name="AMZN")
        )
fig_left.add_trace(
            go.Scatter(x=data['Date'], y=data['QCOM']['Adj Close'], name="QCOM")
        )
fig_left.add_trace(
            go.Scatter(x=data['Date'], y=data['META']['Adj Close'], name="META")
        )
fig_left.add_trace(
            go.Scatter(x=data['Date'], y=data['NVDA']['Adj Close'], name="NVDA")
        )
fig_left.add_trace(
            go.Scatter(x=data['Date'], y=data['JPM']['Adj Close'], name="JPM")
        )
fig_left.update_layout(paper_bgcolor="#14151b", plot_bgcolor="#14151b", font_color="white")

plot_div_left = plot(fig_left, auto_open=False, output_type='div')

[*********************100%***********************]  6 of 6 completed

In [3]:
data

          Date        META                                                  \
                      Open        High         Low       Close   Adj Close
0   2023-03-21  203.199997  203.550003  197.949997  202.160004  201.945740
1   2023-03-22  202.500000  207.369995  199.669998  199.809998  199.598221
2   2023-03-23  202.839996  207.880005  202.149994  204.279999  204.063492
3   2023-03-24  205.179993  207.580002  203.550003  206.009995  205.791641
4   2023-03-27  204.809998  205.860001  201.360001  202.839996  202.625015
..         ...         ...         ...         ...         ...         ...
247 2024-03-14  500.260010  501.350006  488.160004  491.829987  491.829987
248 2024-03-15  489.010010  491.829987  481.299988  484.100006  484.100006
249 2024-03-18  491.910004  497.420013  486.809998  496.980011  496.980011
250 2024-03-19  488.170013  496.630005  481.279999  496.239990  496.239990
251 2024-03-20  499.500000  508.200012  495.170013  505.519989  505.519989

                     QCOM                          ...        AAPL  \
       Volume        Open        High         Low  ...         Low
0    31827000  122.989998  125.070000  122.150002  ...  156.539993
1    28477800  124.000000  126.239998  121.870003  ...  157.809998
2    27389700  123.940002  127.000000  122.099998  ...  157.679993
3    27716400  123.629997  124.930000  122.250000  ...  157.850006
4    18527200  125.739998  126.059998  123.320000  ...  157.869995
..        ...         ...         ...         ...  ...         ...
247  12620000  169.600006  169.949997  166.710007  ...  172.050003
248  29141700  167.100006  168.770004  165.850006  ...  170.289993
249  11755300  170.910004  171.460007  166.350006  ...  173.520004
250  10903100  166.089996  166.460007  163.630005  ...  173.029999
251  11672300  164.100006  168.169998  163.830002  ...  175.089996

                                               JPM                          \
          Close   Adj Close     Volume        Open        High         Low
0    159.279999  158.434326   73938300  130.589996  131.729996  130.190002
1    157.830002  156.992020   75701800  130.559998  130.660004  127.080002
2    158.929993  158.086166   67622100  127.900002  129.529999  126.019997
3    160.250000  159.399170   59196500  125.629997  125.680000  123.110001
4    158.279999  157.439651   52390300  126.790001  129.380005  126.290001
..          ...         ...        ...         ...         ...         ...
247  173.000000  173.000000   72913500  191.029999  191.630005  187.100006
248  172.619995  172.619995  121664700  186.479996  190.940002  186.479996
249  173.720001  173.720001   75604200  190.630005  192.699997  189.889999
250  176.080002  176.080002   55215200  192.710007  193.929993  192.380005
251  178.669998  178.669998   53195300  194.190002  196.559998  193.610001


          Close   Adj Close    Volume
0    130.550003  126.924911  17807800
1    127.180000  123.648476  17250200
2    126.839996  123.317917  16677600
3    124.910004  121.441521  22311100
4    128.490005  124.922112  18853900
..          ...         ...       ...
247  187.970001  187.970001  10310900
248  190.300003  190.300003  17208100
249  192.660004  192.660004   9013800
250  193.789993  193.789993   8478700
251  196.330002  196.330002   9363800

[252 rows x 37 columns]

In [5]:
# function to calculate percentage difference considering baseValue as 100%
def percentageChange(baseValue, currentValue):
    return((float(currentValue)-baseValue) / abs(baseValue)) *100.00

# function to get the actual value using baseValue and percentage
def reversePercentageChange(baseValue, percentage):
    return float(baseValue) + float(baseValue * percentage / 100.00)

# function to transform a list of values into the list of percentages. For calculating percentages for each element in the list
# the base is always the previous element in the list.
def transformToPercentageChange(x):
    baseValue = x[0]
    x[0] = 0
    for i in range(1,len(x)):
        pChange = percentageChange(baseValue,x[i])
        baseValue = x[i]
        x[i] = pChange

# function to transform a list of percentages to the list of actual values. For calculating actual values for each element in the list
# the base is always the previous calculated element in the list.

dictionaryofdateandprice={}

def reverseTransformToPercentageChange(baseValue, x):
    x_transform = []
    for i in range(0,len(x)):
        value = reversePercentageChange(baseValue,x[i])
        baseValue = value
        x_transform.append(value)
    return x_transform

In [6]:
def datapred(ticker_name, number_of_days):
    df = yf.download(tickers=ticker_name,group_by = 'ticker',threads=True,period='12mo',interval='1d')
    df.reset_index(level=0, inplace=True)
    
    baseValue = df['Close'][0]

    # create a new dataframe which is then transformed into relative percentages
    data = df.sort_index(ascending=True, axis=0)
    new_data = pd.DataFrame(index=range(0,len(df)),columns=['Date', 'Close'])
    for i in range(0,len(data)):
        new_data['Date'][i] = data['Date'][i]
        new_data['Close'][i] = data['Close'][i]

    # transform the 'Close' series into relative percentages
    transformToPercentageChange(new_data['Close'])

    # set Dat column as the index
    new_data.index = new_data.Date
    new_data.drop('Date', axis=1, inplace=True)

    # create train and test sets
    dataset = new_data[0:1500].values
    print("====dataset====")
    print(dataset)
    print("====len dataset====")
    print(len(dataset))
    train, valid = train_test_split(dataset, train_size=0.99, test_size=0.01, shuffle=False)

    # convert dataset into x_train and y_train.
    # prediction_window_size is the size of days windows which will be considered for predicting a future value.

    prediction_window_size = 60
    x_train, y_train = [], []
    for i in range(prediction_window_size,len(train)):
        x_train.append(dataset[i-prediction_window_size:i,0])
        y_train.append(dataset[i,0])
    x_train, y_train = np.array(x_train).astype(np.float32), np.array(y_train).astype(np.float32)
    x_train = np.reshape(x_train, (x_train.shape[0],x_train.shape[1],1))


    # X_train = []
    # y_train = []
    # for i in range(60, 1500):
    #     X_train.append(np.array(dataset[60:1600].astype(np.float32))[i-60:i])
    #     y_train.append(np.array(dataset[60:1600].astype(np.float32))[i])
    # X_train, y_train = np.array(X_train), np.array(y_train)
    # X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))



    x_valid, y_valid = [], []
    for i in range(60,120):
        x_valid.append(dataset[i-prediction_window_size:i,0])
        y_valid.append(dataset[i,0])
        
    X_test = np.asarray(x_valid).astype('float32')
    #y_test = np.asarray(y_valid).astype('float32')

    X_test = np.array(X_test)
    X_test = np.reshape(X_test, (X_test.shape[0],X_test.shape[1],1))


    ##################################################################################################
    # create and fit the LSTM network
    # Initialising the RNN
    model = Sequential()
    # Adding the first LSTM layer and some Dropout regularisation
    model.add(LSTM(units = 50, return_sequences = True, input_shape = (x_train.shape[1], 1)))
    model.add(Dropout(0.2))

    # Adding a second LSTM layer and some Dropout regularisation
    model.add(LSTM(units = 50, return_sequences = True))
    model.add(Dropout(0.2))

    # Adding a third LSTM layer and some Dropout regularisation
    model.add(LSTM(units = 50, return_sequences = True))
    model.add(Dropout(0.2))

    # Adding a fourth LSTM layer and some Dropout regularisation
    model.add(LSTM(units = 50))
    model.add(Dropout(0.2))

    # Adding the output layer
    model.add(Dense(units = 1))
    # Compiling the RNN
    model.compile(optimizer = 'adam', loss = 'mean_squared_error')
    # accu = model.evaluate(x_test,y_test)
    # print("accuracy is")
    # print(acu)
    # Fitting the RNN to the Training set
    model.fit(x_train, y_train, epochs = 10, batch_size = 1000)

    df_ml = df[['Adj Close']]
    forecast_out = int(number_of_days)
    df_ml['Prediction'] = df[['Adj Close']].shift(-forecast_out)
    # Splitting data for Test and Train
    X = np.array(df_ml.drop(['Prediction'],1))
    X = preprocessing.scale(X)
    X_forecast = X[-forecast_out:]
    X = X[:-forecast_out]
    y = np.array(df_ml['Prediction'])
    y = y[:-forecast_out]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

    X_forecast = np.array(X_forecast).astype(np.float32)
    X_forecast = np.reshape(X_forecast, (X_forecast.shape[0],X_forecast.shape[1],1))

    forecast_prediction = model.predict(X_forecast)
    forecast = forecast_prediction.tolist()

    pred_dict = {"Date": [], "Prediction": []}
    for i in range(0, len(forecast)):
        pred_dict["Date"].append(dt.datetime.today() + dt.timedelta(days=i))
        pred_dict["Prediction"].append(forecast[i][0])
        
    pred_df = pd.DataFrame(pred_dict)
        
    pred_fig = go.Figure([go.Scatter(x=pred_df['Date'], y=pred_df['Prediction'])])
    pred_fig.update_xaxes(rangeslider_visible=True)
    pred_fig.update_layout(paper_bgcolor="#14151b", plot_bgcolor="#14151b", font_color="white")
    plot_div_pred = plot(pred_fig, auto_open=False, output_type='div')
    
    return pred_df

In [7]:
ticker_name = 'AMZN'
number_of_days = 30
pred_df = datapred(ticker_name, number_of_days)
pred_df

[*********************100%***********************]  1 of 1 completed
====dataset====
[[0]
 [-1.089568130057839]
 [-1.2531560404374114]
 [2.967968020726093]
 [-1.898423268583957]
 [0.010133876939949474]
 [-0.587581639584802]
 [-0.0917113425145748]
 [-0.815996577200266]
 [3.0954362426533533]
 [1.7456359102244388]
 [1.2647067799287683]
 [-0.8519675143943976]
 [1.5037527888523978]
 [-2.7417013542964686]
 [0.9495540049077156]
 [0.10778033801971233]
 [-2.2022120390757625]
 [-2.091669711959809]
 [4.67136830142994]
 [0.10742246944572822]
 [0.22436418178336404]
 [-0.42826048390145]
 [1.9550341547772163]
 [-0.4698039106680585]
 [3.034391291745232]
 [-0.7011967150520266]
 [-3.427172037496596]
 [2.3496184744855624]
 [4.610398345515921]
 [-3.9792412663683407]
 [-3.2242712137328815]
 [1.548254928379388]
 [0.019303553981593596]
 [0.33767339022538034]
 [1.5961573674128606]
 [0.16089169321718977]
 [0.7464810562778676]
 [3.3483395262233415]
 [1.80596952507349]
 [-1.7115333960796282]
 [0.8525256609829547]
 [1.9784214370623647]
 [1.8518504813616383]
 [2.2943736154795724]
 [-1.6081265352017287]
 [-1.066664829049059]
 [-0.017393506729303634]
 [1.5305697616548972]
 [-1.4989293361884368]
 [4.443478791610055]
 [1.2904862574983844]
 [-0.8877213533991127]
 [1.8162172655131759]
 [1.2055089984537999]
 [0.8450728786783199]
 [1.0454888481148943]
 [-4.249267220189953]
 [2.4911297199050035]
 [-0.6599595129369971]
 [2.5439515368102676]
 [0.07111003199981579]
 [-0.18948798849266155]
 [0.5458016543269869]
 [-1.2744888197649036]
 [0.23109484458049426]
 [-0.7552845901271824]
 [4.261789623803565]
 [-0.6300361919969611]
 [-1.5464315871677043]
 [1.4529104045574321]
 [-0.10837544324670384]
 [-0.8834406537251538]
 [1.923376900018963]
 [-0.10739443770554916]
 [0.12287180203461455]
 [-1.5493205988729235]
 [1.1062622017709753]
 [-2.041918285409668]
 [1.2978852839820578]
 [1.5685698801122214]
 [2.6758409161619388]
 [0.282940890088434]
 [-0.8315972513331614]
 [-0.546567640673105]
 [1.9046892602732612]
 [-3.989357175040833]
 [0.030773533446228327]
 [-0.9230745755709134]
 [0.25621259567989096]
 [-0.758933593487819]
 [0.07803832093539298]
 [3.087724533229776]
 [1.1118568090654815]
 [-1.4886223394710927]
 [-2.642566377874768]
 [0.5459768439170325]
 [8.269337801006268]
 [1.8986843572548393]
 [-1.6031491771390682]
 [-1.4934945701217344]
 [0.5150463718840691]
 [-0.10825194798444343]
 [1.5605834874352293]
 [-2.0630355012962966]
 [-1.8885675014943462]
 [-0.8069975106044455]
 [-0.5672447612115602]
 [1.0959251176250808]
 [-0.31926989840011566]
 [0.9459994580714618]
 [-2.715472121128119]
 [1.0770617478674847]
 [-0.09004586682715533]
 [1.3294308852149164]
 [0.11860029483811614]
 [2.1766395374215937]
 [0.07970481467276193]
 [-0.615400285820594]
 [-1.391420997057956]
 [1.8395430569860982]
 [0.2756544121863093]
 [3.5231212663680407]
 [-1.3067856717097797]
 [2.5632022130484855]
 [-0.0897513823503696]
 [-2.991985761837634]
 [-0.29204620264398007]
 [-1.6788047695762542]
 [-1.700219075536713]
 [-4.405345369833071]
 [-0.16238050792075434]
 [1.6651248734342958]
 [-4.029862682526879]
 [0.0]
 [0.0]
 [0.904905031966484]
 [1.8407834461347774]
 [-3.661366636292885]
 [1.8280939360016637]
 [-0.8188983586829478]
 [1.587805664128926]
 [0.23444468936361867]
 [0.9511938819224743]
 [1.8149568899126884]
 [0.3792763354739004]
 [-1.9194502454286186]
 [2.1265196921155005]
 [-0.8147882355257063]
 [-2.54050072783042]
 [0.21071490157110861]
 [-2.5155731161039414]
 [1.110489262588562]
 [1.5802781594350581]
 [-5.577161096069129]
 [-1.4992995337138288]
 [6.832816082459992]
 [3.8907225091689805]
 [0.2863308000900971]
 [2.9378644298573775]
 [0.7810272439552919]
 [0.38386235328598284]
 [0.8225103459209163]
 [2.1253764877291452]
 [-0.4414580990635481]
 [-1.0416636461610582]
 [2.1052569890351607]
 [-0.6756765374750169]
 [2.2512145285848417]
 [-1.783268895126596]
 [-0.2583764839891931]
 [1.6453061783939695]
 [0.6543685459144742]
 [-1.5260459261028974]
 [1.9527539517508372]
 [0.02044767086363952]
 [0.6746559883569849]
 [-0.47383535401517496]
 [-0.4828888396740557]
 [-0.15719722171586703]
 [0.643440663269047]
 [-1.4894936132684113]
 [1.4084566393959523]
 [-1.6067541747663185]
 [1.632992347483118]
 [0.3676424756137798]
 [-1.0378502226973818]
 [1.089859719338269]
 [0.9221593773735162]
 [-0.9540434049203341]
 [1.729753821347545]
 [2.733884156926729]
 [-0.18174467759755938]
 [-1.085895208954337]
 [1.1306871390431619]
 [-0.27300973670256606]
 [-0.006514474615578864]
 [-0.045634132421340304]
 [0.026091395511523698]
 [-0.9388462612883998]
 [-1.322897020750105]
 [-0.9737821159208012]
 [-2.626789159034874]
 [0.4634420246259977]
 [2.657670383063459]
 [1.522460711434103]
 [1.5590940651907264]
 [0.943210166226809]
 [-0.36086969005325137]
 [-0.9442449238027643]
 [-0.9467203666572552]
 [1.1798781932089892]
 [1.1986946826649023]
 [-0.3604979862209222]
 [0.8011406531487346]
 [0.5447960655367026]
 [0.5609771850602181]
 [0.8684596622424722]
 [1.3448965908227857]
 [-1.4014601164705698]
 [-2.389939026262775]
 [2.628867210877157]
 [7.866649218561846]
 [-0.8730574595861006]
 [-0.6811130754143105]
 [0.8158468416244987]
 [-0.404622322374648]
 [2.714319777292111]
 [-1.2095159915523424]
 [-2.146917156124313]
 [1.3875689909628048]
 [-0.6901349311422361]
 [-0.1707941929974381]
 [-1.4335394693693144]
 [0.9037553808281554]
 [3.553001733957454]
 [0.2348514479374021]
 [-0.14858549486425224]
 [-0.6810521779339199]
 [-0.21896371944472212]
 [2.0789967478582976]
 [0.8259825521836186]
 [-0.3591063770984259]
 [-1.9484213752621504]
 [-0.35033346396605136]
 [1.9076784751165472]
 [-0.831354575168475]
 [-1.933275889164894]
 [1.9946455814511483]
 [0.667083740815821]
 [1.2403729449981833]
 [-2.4223786467438813]]
====len dataset====
252
Epoch 1/10
1/1 [==============================] - 0s 2ms/step - loss: 3.5042
Epoch 2/10
1/1 [==============================] - 0s 0s/step - loss: 3.4977
Epoch 3/10
1/1 [==============================] - 0s 0s/step - loss: 3.4797
Epoch 4/10
1/1 [==============================] - 0s 997us/step - loss: 3.4674
Epoch 5/10
1/1 [==============================] - 0s 999us/step - loss: 3.4665
Epoch 6/10
1/1 [==============================] - 0s 0s/step - loss: 3.4610
Epoch 7/10
1/1 [==============================] - 0s 998us/step - loss: 3.4738
Epoch 8/10
1/1 [==============================] - 0s 998us/step - loss: 3.4756
Epoch 9/10
1/1 [==============================] - 0s 0s/step - loss: 3.4480
Epoch 10/10
1/1 [==============================] - 0s 998us/step - loss: 3.4496
WARNING:tensorflow:Model was constructed with shape (None, 60, 1) for input Tensor("lstm_input:0", shape=(None, 60, 1), dtype=float32), but it was called on an input with incompatible shape (None, 1, 1).

C:\Users\sushant\AppData\Local\Temp\ipykernel_14304\3420673225.py:95: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\sushant\AppData\Local\Temp\ipykernel_14304\3420673225.py:97: FutureWarning:

In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only

                         Date  Prediction
0  2024-03-18 10:35:10.524905    0.019411
1  2024-03-19 10:35:10.524905    0.019439
2  2024-03-20 10:35:10.524905    0.019462
3  2024-03-21 10:35:10.524905    0.019435
4  2024-03-22 10:35:10.524905    0.019448
5  2024-03-23 10:35:10.524905    0.019363
6  2024-03-24 10:35:10.524905    0.019401
7  2024-03-25 10:35:10.524905    0.019472
8  2024-03-26 10:35:10.524905    0.019427
9  2024-03-27 10:35:10.524905    0.019449
10 2024-03-28 10:35:10.524905    0.019455
11 2024-03-29 10:35:10.524905    0.019504
12 2024-03-30 10:35:10.524905    0.019473
13 2024-03-31 10:35:10.524905    0.019360
14 2024-04-01 10:35:10.524905    0.019353
15 2024-04-02 10:35:10.524905    0.019358
16 2024-04-03 10:35:10.524905    0.019379
17 2024-04-04 10:35:10.524905    0.019386
18 2024-04-05 10:35:10.524905    0.019323
19 2024-04-06 10:35:10.524905    0.019298
20 2024-04-07 10:35:10.524905    0.019309
21 2024-04-08 10:35:10.524905    0.019369
22 2024-04-09 10:35:10.524905    0.019379
23 2024-04-10 10:35:10.524905    0.019322
24 2024-04-11 10:35:10.524905    0.019347
25 2024-04-12 10:35:10.524905    0.019408
26 2024-04-13 10:35:10.524905    0.019346
27 2024-04-14 10:35:10.524905    0.019326
28 2024-04-15 10:35:10.524905    0.019290
29 2024-04-16 10:35:10.524905    0.019363

In [8]:
dff = pd.read_csv("Fortune_1000.csv")
dff

,company,rank,rank_change,revenue,profit,num. of employees,sector,city,state,newcomer,ceo_founder,ceo_woman,profitable,prev_rank,CEO,Website,Ticker,Market Cap
0,Walmart,1,0.0,572754.0,13673.0,2300000.0,Retailing,Bentonville,AR,no,no,no,yes,1.0,C. Douglas McMillon,https://www.stock.walmart.com,WMT,352037
1,Amazon,2,0.0,469822.0,33364.0,1608000.0,Retailing,Seattle,WA,no,no,no,yes,2.0,Andrew R. Jassy,www.amazon.com,AMZN,1202717
2,Apple,3,0.0,365817.0,94680.0,154000.0,Technology,Cupertino,CA,no,no,no,yes,3.0,Timothy D. Cook,www.apple.com,AAPL,2443962
3,CVS Health,4,0.0,292111.0,7910.0,258000.0,Health Care,Woonsocket,RI,no,no,yes,yes,4.0,Karen Lynch,https://www.cvshealth.com,CVS,125204
4,UnitedHealth Group,5,0.0,287597.0,17285.0,350000.0,Health Care,Minnetonka,MN,no,no,no,yes,5.0,Andrew P. Witty,www.unitedhealthgroup.com,UNH,500468
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Vizio Holding,996,0.0,2124.0,-39.4,800.0,Industrials,Irvine,CA,no,yes,no,no,,William W. Wang,https://www.vizio.com,VZIO,1705.1
996,1-800-Flowers.com,997,0.0,2122.2,118.7,4800.0,Retailing,Jericho,NY,no,no,no,yes,,Christopher G. McCann,https://www.1800flowers.com,FLWS,830
997,Cowen,998,0.0,2112.8,295.6,1534.0,Financials,New York,NY,no,no,no,yes,,Jeffrey Solomon,https://www.cowen.com,COWN,1078
998,Ashland,999,0.0,2111.0,220.0,4100.0,Chemicals,Wilmington,DE,no,no,no,yes,,Guillermo Novo,https://www.ashland.com,ASH,5601.9
999,DocuSign,1000,0.0,2107.2,-70.0,7461.0,Technology,San Francisco,CA,no,no,no,no,,Allan C. Thygesen,https://www.docusign.com,DOCU,21302.8

In [9]:
cmp_ticker = dff[dff["company"]=="CVS Health"]
cmp_ticker["Ticker"].values[0]

'CVS'